project:
  type: website

website:
  title: "作物养分管理课题组"
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: about.qmd
        text: 课题组简介
      - href: team.qmd
        text: 教师团队  
      - href: research.qmd
        text: 研究方向
      - href: publications.qmd
        text: 发表论文
      - href: contact.qmd
        text: 联系我们

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "目录"
    highlight-style: github
    code-fold: true

github-pages:
  branch: main
  provider: github
