---
title: "团队成员"
---

## 教师团队

### 鲁剑巍 教授
- 研究方向：现代施肥技术、施肥与农产品安全、施肥与生态环境、土壤肥力
- 邮箱：lujianwei@mail.hzau.edu.cn
- 个人简介（学术兼职）：
国家油菜产业技术体系“养分管理与施肥”岗位科学家（2008-　）
农业农村部科学施肥专家指导组成员（2005-2017，农业部测土配方施肥技术专家组；2018-　）
农业农村部肥料登记评审委员会委员（第八届2015-2018；第九届2019-2022）
湖北省测土配方施肥技术专家组成员（2006-　）
中国植物营养与肥料学会理事（2007-2021），兼副秘书长（2012-2021）
中国农学会油料作物专业委员会理事（2011-　）
中国土壤学会土壤肥力与肥料专业委员会委员（2016-2020）
湖北省土壤肥料学会常务理事（2005-　）
湖北省肥料应用协会副理事长（2011-2015）
农业部长江中下游耕地保育重点实验室副主任（2011-2015）
湖南省耕地质量建设与管理技术顾问（2011-　）
新型肥料湖北省工程实验室副主任（2013-2015）
《中国土壤与肥料》编委（2012-　）
《中国油料作物学报》编委（2015-　）
《植物营养与肥料学报》编委（2017-　）
《中国农业科学》编委（2017-　）
《土壤》编委（2019-　）

### 李小坤 教授
- 研究方向：
1 水稻营养与施肥、稻田地力提升
2 水旱轮作体系养分管理、稻田综合种养体系养分管理
3 钾素营养与钾肥、作物专用肥的研发、现代施肥技术
- 邮箱：lixiaokun@mail.hzau.edu.cn
- 科研项目：
1. 校企合作，作物专用肥料配方研制，2025-2026。主持
2. 省水稻产业体系岗位科学家，科学施肥，2024-2026。主持
3. 国家重点研发计划子课题，土壤固碳与产能提升，2023-2027。主持
4 委托项目，植烟土壤适应性，2023-2025。主持
5 委托项目，烟叶品质调控，2023-2025。主持
6 国家农业重大科技项目子课题，肥水高效利用，2022-2026。主持
7 国家重点研发计划子课题，中低产稻田产能提升，2021-2025。主持

### 任涛 教授
- 研究方向：作物营养生理与养分管理
- 邮箱：rentao@mail.hzau.edu.cn
- 个人简介： 国家油菜产业技术体系“养分管理与施肥”岗位成员，担任了《中国油料作物学报》、《Oil Crop Science》青年编委、中国植物营养与肥料学会青年工作委员会、施肥专业技术委员会以及中国自然资源学会农业资源利用专业委员会委员。先后主持了国家自然科学基金、国家重点研发计划子课题等项目10多项。以第一或通讯作者在New Phytologist、Plant, Cell & Environment、Field Crops Research、the Crop Journal、土壤学报、作物学报、植物营养与肥料学报等期刊发表学术论文60多篇。出版专著2部，参编专著4部，获得授权发明专利8项，参与起草农业行业标准1项和湖北省地方标准4项，先后获得湖北省科技进步奖一等奖2项、二等奖1项、神农中华农业科技二等奖1项和中国自然资源学会青年科技奖。

### 丛日环 副教授
- 研究方向：作物养分管理与土壤肥力培育
- 邮箱：congrh@mail.hzau.edu.cn
- 个人简介： 国家油菜产业技术体系“养分管理与施肥”岗位成员，湖北省秸秆综合利用技术专家组成员，中国植物营养与肥料学会化学肥料专业委员会、养分循环与环境专业技术委员会委员。现主要从事作物养分管理和土壤肥力培育方面的教学和研究工作。主持国家自然科学基金、国家重点研发计划子课题、湖北省自然科学基金、校自主创新基金等项目。获得奖励5项，授权专利3项，参与制定农业行业标准1项。编写专著7部，发表学术论文100余篇，其中以第一作者或通讯作者发表学术论文30余篇。

### 陆志峰 副教授
- 研究方向：主要从事作物镁、钾营养机理和养分管理研究工作，重点开展高光效、高产和高品质作物的养分调控机理和应用技术研究
- 邮箱：zhifenglu@mail.hzau.edu.cn
- 科学研究
承担的主要科研项目：
（1）国家重点研发计划子课题“华中中低产田土壤固碳与产能提升协同技术模式筛选及示范”， 2023.04-2027.04，主持
（2）国家自然科学基金面上项目“缺镁对细胞能量平衡的影响及其诱发油菜叶片光氧化的机理”，2023.01-2026.12，主持
（3）国家农业重大科技攻关项目子课题“长江中游秸秆高效还田技术与应用”，2022.11-2026.12，主持
（4）国家重点研发计划子课题“稻-油机械化种植周年产量与品质协同提升生理机制”， 2022.11-2025.12，主持
（5）国际镁营养研究所合作项目“全国镁营养研究协作网试验及示范”， 2022.01-2024.12，主持
（6）中央高效基本科研业务费专项基金“镁营养调控油菜叶片CO2运输和利用的机理研究”，2021.01-2023.12，主持
（7）国家重点研发计划 “科技助力经济2020”重点专项“油菜高效缓释专用肥配方优化与施用技术研究”，2020.07-2022.12，主持（已结题）
（8）国家自然科学基金青年基金项目“钾素营养优化油菜叶片光合的水-碳协调机制解析”，2019.01-2021.12，主持（已结题）
（9）中国博士后基金“钾素协调单子叶和双子叶叶片水分运输和光合能力的机制解析”，2017.03-2018.12，主持（已结题）
（10）中央高校基本科研业务费专项基金 “钾素营养优化油菜叶片光合的水-碳协调机制解析”， 2019.01-2019.12，主持（已结题）

## 刘诗诗 教授
- 研究方向：农业遥感
- 个人简介：毕业于美国加州圣芭芭拉大学地理系， 2013年加入华中农业大学资源与环境学院担任副教授、硕士生导师、地理信息系副系主任。刘诗诗自攻读博士起致力于利用多光谱、高光谱遥感技术研究环境胁迫对植被生长的影响，通过挖掘植被在环境胁迫下的光谱特征，构建精准的植被参数反演模型，探测作物的养分、水分胁迫状态，根据作物养分需求推荐追肥量，进一步预测作物产量，服务精准农业。目前已在遥感、农业类SCI收录期刊发表学术论文二十余篇，并且担任多个国际知名学术期刊的审稿人。
- 科研项目：
1.国家自然科学基金面上项目，42171350，顾及冠层结构影响的作物叶片氮含量遥感反演方法研究，2022/01 – 2025/12，经费52万元，在研，主持。
2.国家重点研发计划课题，2021YFD1600503，山区油菜产业智能化关键技术和机械装备研究示范，2021/12 – 2026/11，可支配经费50万元，参与。
## 朱俊 副教授
- 研究方向：土壤有机质
- 个人简介：农业生物学与农业化学博士，承担土壤与环境类课程的教学工作，从事有机质转化过程的微观机制及环境、生态和肥力效应方面的科研工作，现已发表SCI(第一作者、通讯作者)论文9篇，主持国家自然科学(青年)基金1项，教育部留学回国人员科研启动基金1项。

## 张文君 副教授
- 研究方向：土壤—植物养分循环与转化；土壤磷化学；植物硅营养
- 科研项目：
1.国家农业重大科技项目子课题 主持2022-2026
2.国家重点研发计划项目子课题 主持 2018-2021
3.校自主科技创新基金项目 主持2017-2019
4.国家自然科学基金 主持 2014-2016
5.教育部博士点基金项目 主持 2014-2016
6.大学生科技创新基金 主持2014-2015

## 在读研究生
课题组现有在读博士研究生21人，硕士研究生53人。

